services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pg_data_1:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER ']
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    tty: true
    ports:
      - '8000:8000'
    command: sh -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  pgadmin:
    container_name: pgadmin8_container
    image: dpage/pgadmin4:8.14.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pg_data_1:
  pgadmin-data: